### ISSUE TITLE
Surfacing Bikeshed warnings better

### ISSUE THREAD

**Issue by domenic** [whatwg/meta#24] opened 2017-03-30 03:52 UTC
Because in CI we use the Bikeshed web service, which I don't believe provides any way of seeing warnings, it's easy to commit spec changes that induce warnings without ever noticing.

Similar issues occur when someone wants to use `make remote`.

I'm not sure what the best solution is for this. /cc @tabatkins. Maybe what we need is a mode for the web service that will fail if there are any warnings? But hmm, we want to intentionally ignore the security/privacy warnings. Not sure...

**Comment by annevk** [comment] 2017-03-30 04:18
We could just set the acceptable output in stone. Although we'd have to do some work to make sure all documents are aligned. They also not all use the centralized processing yet.

**Comment by foolip** [comment] 2017-03-30 04:21
-Werror, or are there any warning that we don't want to fix? Or is the problem that Bikeshed changes can introduce warnings and we don't want to fail hard because of that?

**Comment by annevk** [comment] 2017-03-30 04:28
We ignore some privacy/security section warning at the moment. A generic section for that is not always the best solution.

If Bikeshed changes and we get new warnings, it seems reasonable to then fail builds.

**Comment by annevk** [comment] 2017-03-30 04:30
(Might be interesting to run the build tools whenever Bikeshed changes for all standards, to catch regressions that way. And generate diffs of the generated HTML for review.)

**Comment by zcorpan** [comment] 2017-03-31 13:13
Maybe bikeshed could support a metadata line to silence the privacy section warning?

**Comment by tabatkins** [comment] 2017-03-31 20:38
Yeah, I can do that.

I'd also support an "upgrade all non-fatal errors to fatal" option.

Longer-term, I want to give every error an identifier, so I can document all of them and let you selectively silence/upgrade individual ones you care about.

**Comment by annevk** [comment] 2018-01-08 09:47
To update this thread too. What I've done in https://github.com/whatwg/whatwg.org/pull/160 is to invoke Bikeshed first with output=err to get any link errors/warnings and only then start building (invoking Bikeshed again). The idea is that once we get all those to zero for all standards we can make it a fatal error.

If Bikeshed at some point supports returning either a complete document or a set of errors we could turn those two invocations into one.

I think we need to do the same for `make remote`. Basically make that invoke the Bikeshed API twice. First to get error output, then to get the document. We could make that one fail more aggressively I suppose.

Does that make sense?

**Comment by domenic** [comment] 2018-01-08 18:53
I think Bikeshed does support that. Right now we're using `-f` with curl which causes failures on non-ok status codes. But if we omit that then it'll output the errors as the body on failure, and the actual body as the body on success. We just need to be cleverer about checking the status code... not sure how to do that, exactly.

https://github.com/whatwg/html-build/blob/1f2386366e3580019699f0915a032f508a38453c/build.sh#L376 isn't quite what we need but may give some inspiration.

**Comment by annevk** [comment] 2018-01-09 12:19
@domenic that might work, if Bikeshed had a mode where warnings would be fatal. Otherwise we'd still end up missing using "must" in a note, for instance. So I think for now we need to use two requests.

**Comment by annevk** [comment] 2019-09-25 17:48
This ended up being fixed in https://github.com/whatwg/whatwg.org/commit/c4fcc3fa9efee7829176261ea7a568bbc6d50ccf.

**Closed by annevk** 2019-09-25 17:48 UTC

**Comment by domenic** [comment] 2019-09-26 00:29
Note though that it is only fixed if you use make deploy, and not make remote :/.
