### ISSUE TITLE
Invitation to attend upcoming IETF meetings

### ISSUE THREAD

**Issue by domenic** [whatwg/meta#58] opened 2017-12-13 23:21 UTC
@mnot has extended an invite to the @whatwg/sg or other members of the WHATWG community who might want to attend [the IETF meeting in London in March 2018](https://ietf.org/meeting/101/index.html), or [any other upcoming meetings](https://ietf.org/meeting/upcoming.html). This could be a good opportunity for cross-pollination between the two communities, and I wanted to share it more widely.

**Comment by mnot** [comment] 2017-12-13 23:31
Specifically, if you need any help / advice regarding how best to engage or get value out of coming, please feel free to ping me; if I can't answer questions, I'll get you in touch with someone who can.

**Comment by foolip** [comment] 2017-12-13 23:31
Cool, much appreciated. @alvestrand, will you be there?

**Comment by othermaciej** [comment] 2017-12-14 02:46
Is there any general advice for attending? I'm an SG representative but I am not sure I could usefully contribute to any IETF WG meetings. What else is there to do?

**Comment by mnot** [comment] 2017-12-14 03:13
One of the reasons that I want to get more cross-pollination is to help IETF folks understand WHATWG and what they're doing, and vice versa. So actively contributing to WG is great, but there's still value in coming if you don't.

Like many standards meetings, much of the value is in the hallways / dinners / etc., as well as the informal side meetings. I'm happy to make introductions, point you towards potentially interesting events, etc.

That said, the WGs that might be useful to check out include:

- DISPATCH/ARTAREA - area meeting for application-layer stuff
- HTTP
- TLS
- QUIC
- DOH - DNS over HTTP
- JSONBIS
- NETVC - royalty-free video codec
- RTCWEB
- MAPRG - interesting presentations about internet measurement
- SAAG - security area general meeting

For details, see:
  https://datatracker.ietf.org/wg/

**Comment by masinter** [comment] 2017-12-14 20:02
The IETF/WHATWG conflicts that I see need resolution are the URL mess (URI, IRI, URL), various schemes (mailto, file, ftp); some MIME types (multipart/form-data), MIME types in general (the IANA 'magic number' registry vs. MIME type sniffing).  

"conflicts":  overlapping specs from different orgs covering same topic, specs don't match and none completely "match reality".

**Comment by othermaciej** [comment] 2017-12-14 20:26
@masinter What are good forums to discuss those areas of overlap? Would there be a session at the London IETF meeting where they could be brought up? Alternately, are there IETF WGs that the proper WHATWG Workstreams could work with? (Relevant Workstreams for that would be URL, MIME Sniffing and HTML, I believe).

**Comment by masinter** [comment] 2017-12-14 21:50
@othermaciej the forum is ARTAREA/DISPATCH, which handles non-WG activities in applications and real-time.  @mnot and/or area directors might have other ideas

**Comment by jgraham** [comment] 2017-12-14 22:19
I'm already in London, so I can easily attend that meeting. I'm happy to do so if it's likely to have value.

**Comment by othermaciej** [comment] 2017-12-14 23:03
Sounds like possible areas of useful engagement are:
1. hallway conversations and side events for relationship building
2. DISPATCH/ARTAREA for discussion of URL, MIME Sniffing and multipart/form-data (assuming they are game to add this agenda item)

Any other suggestions?

For (2), I think it’s most important to have someone there who is closely engaged in technical work on one or more of those specs, ideally an editor or deputy editor. I think @jgraham is likely to know many of the relevant pieces of info. Having an SG rep along could help too of course.

For the other WGs mentioned, there’s definitely a browser angle of interest, but not sure if there is specifically a WHATWG angle, unless I am missing something.

**Comment by mnot** [comment] 2017-12-14 23:13
It's important to understand that DISPATCH's job is to figure out where the best place to send a proposal in the ART area is, and that any topic is going to be given (at most) a half an hour or so for discussion. I'm not sure bringing up WHATWG work there is going to help, unless WHATWG wants to start publishing work in the IETF.

ARTAREA *might* be an appropriate place to talk about URL, MIME Sniffing and form data, if it's a "hey, just so you know this is what we're doing" kind of presentation. A side meeting might work too.

Honestly, though, my focus is on the first goal @othermaciej pointed out.

**Comment by annevk** [comment] 2018-01-04 11:02
I'll attend IETF 101 as well; arriving on March 18 from 1PM onwards (or so) and leaving March 19 around 5PM. This'll be my second brief attendance. 😊

**Comment by mnot** [comment] 2018-01-23 04:03
I'm talking to some other folks in IETF leadership (IESG and IAB) and there's interest in having someone from WHATWG give a "what is the WHATWG, and what is it doing?" (roughly) presentation to the combined leadership (which usually meets together on Sunday afternoon). 

Would someone from WHATWG (ideally, from SG) be interested in giving that presentation? If so, I'll set the wheels in motion to request it formally. We've also talked about a discussion / meet-and-greet of some sort afterwards.

**Comment by othermaciej** [comment] 2018-01-23 08:54
I think @annevk and @jgraham are both pretty qualified to explain WHATWG, but I would also consider doing it and will check in whether other SG members are interested.

**Comment by annevk** [comment] 2018-02-16 09:36
If that's likely to see attendance I'm happy to (co-)host such a BoF.

**Comment by mnot** [comment] 2018-02-17 00:12
Cool. I can ping a list or two to gauge how much interest there is, if that's OK?

Regarding timing, the [agenda](https://datatracker.ietf.org/meeting/agenda/) is out. How about 19:00 on Sunday, right after the welcome reception? That way people can get a bite or two at the reception, come to talk for ~1 or 1.5 hours, and then go out to dinner.

I can get a room reserved if so.

WRT talking to the IAB/IESG - have we decided who will speak? To be clear, if it's not a SG member that's fine.

**Comment by othermaciej** [comment] 2018-02-17 01:03
It can probably be me but I need to secure one final approval.

Will the IAB/IESF presentation be only to them or will it be a closed session.

**Comment by annevk** [comment] 2018-02-17 07:39
@mnot regarding the BoF, sounds great.

**Comment by mnot** [comment] 2018-02-18 21:43
@othermaciej the meeting is not open to the public; it will be IESG and IAB members, liaisons and a perhaps a couple of invited guests. The minutes are made public ([sample](https://www.iab.org/documents/minutes/minutes-2017/iab-minutes-2017-07-20/)), but they're pretty high-level, and you can request comments to be off the record if necessary.

**Comment by othermaciej** [comment] 2018-02-18 23:15
@mnot Thanks for the clarification. Still waiting on that final approval but the folks I've heard from so far are in favor.

**Comment by mnot** [comment] 2018-02-21 06:35
The minutes of those particular sessions aren't made public.

**Comment by othermaciej** [comment] 2018-02-22 18:23
@mnot I'm now ready to confirm that I can do a presentation for IESG/IAB. Still need to arrange travel. Can you confirm on your end?

Also, do I also need to register to attend IETF 101? My plan is to attend only the IESG/IAB presentation and the BOF.

**Comment by mnot** [comment] 2018-02-26 05:38
@othermaciej confirmed. You're on the agenda at approximately 1:30pm; I'll give you a more exact time /location when it gets nailed down.

Checking into registration, will get back to you ASAP.

**Comment by mnot** [comment] 2018-02-26 05:48
For the BoF, I've booked the IAB room from 7pm-8pm; that's right after the welcome reception, so people can get a small snack beforehand. When we're done, we can migrate to [a local pub](http://thechapellondon.com) that has good food (or at least did last time IETF was there); I've asked for them to hold us a couple of tables at 8.

**Comment by othermaciej** [comment] 2018-02-26 06:29
So that's Sunday the 18th, 1:30PM? And BoF is the same day 7PM-8PM?

**Comment by mnot** [comment] 2018-02-26 07:15
Yes.

**Comment by mnot** [comment] 2018-02-27 00:18
@othermaciej You don't need to register to come and talk with us or to do the Bar BoF. If you'd like to go to the welcome reception (which is between them), tell me and we can get you in, with a bit of arrangement.

**Comment by othermaciej** [comment] 2018-03-04 03:21
I'll be staying at the London Hilton Metropole, arriving the afternoon of March 16th and leaving on the 19th. If anyone is interested in dinner in London on Saturday the 17th, please let me know here or offline.

**Comment by mnot** [comment] 2018-03-17 13:10
@othermaciej the location is:

> Hilton Meeting Rooms 1-4 (Tower Wing 3rd Floor)

Please show up around 1:25pm, and ping me if you have any issues (iMessage mnot@mnot.net, twitter @mnot).

@annevk you're welcome to come along too if you arrive in time.

**Comment by annevk** [comment] 2018-03-17 16:26
I was going to, but (I think) due to weather issues I got bumped to a later flight, arriving at 1PM.

**Comment by othermaciej** [comment] 2018-03-18 13:18
@annevk get in touch when you get in.

**Comment by michaelchampion** [comment] 2018-03-19 16:57
Any interesting discussion to report?

**Comment by mnot** [comment] 2018-03-19 17:22
A fair amount, I think. We talked about:

* Governance - General interest in the new governance model.
* Referencing WHATWG specs - didn't get into details, but highlighted that this is going to be necessary. Talked about living standards.
* Encoding - lots of discussion, agreement that we need to figure out a plan for the IANA registry. Lowest hanging fruit is to put a warning on the registry that "this doesn't apply to the Web", but also interest in exploring whether it can be applied to other things, or the registry can be updated, etc. Also can consider its use in the next revision of the HTTP document set (httptre).
* Mime Sniff - can probably reference from httptre. Some interest in exploring how mail diverges.
* Fetch - Might be good to reference it from [BCP56bis](http://httpwg.org/http-extensions/draft-ietf-httpbis-bcp56bis.html). Should coordinate during httptre to see if HTTP can offer Fetch better hooks/interfaces, take input where appropriate.
* URL - We didn't get to this, but at the pub afterwards, I think people are amenable to further discussion if there's energy to do something.
* General communication - it might be good to consider establishing a liaison relationship at some point.

**Comment by othermaciej** [comment] 2018-03-19 21:38
That summary is pretty good. One thing I'm not sure of is who to follow up with on any of the above points. Like say we wanted to set up an official liaison - who would we talk to and how? Help from @mnot would be appreciated on finding the right points of contact.

**Comment by mnot** [comment] 2018-03-25 14:41
I'm the right point of contact for initiating that discussion.

**Comment by annevk** [comment] 2018-05-29 03:53
Closing this as we attended and had a good discussion.

**Closed by annevk** 2018-05-29 03:53 UTC
