### ISSUE TITLE
Steps On Standardizing Refresh Rate Behaviours With Web Browsers (120 Hz, 144 Hz, 240 Hz...)

### ISSUE THREAD

**Issue by mdrejhon** [whatwg/meta#159] opened 2020-01-16 23:08 UTC
Now that I (founder) and Blur Busters (organization) has formally joined the WHATWG standards process, I'd like to introduce myself -- I'm the creator of the popular [www.testufo.com](https://www.testufo.com) motion tests that you now see in the news relating to almost anything high-Hz.

### The Need To Standardize Browser Behaviour For High-Hz Display Technologies

There is a browser consistency problem with standardization of animations at high refresh rates.

### First, My Credentials

For those unfamiliar with my work in high-Hz, I'm the founder of [BlurBusters.com](https://www.blurbusters.com) and creator of [TestUFO.com](https://www.testufo.com), and have a [Display Engineering](https://forums.blurbusters.com/viewforum.php?f=7) discussion forum. I've got references in a [paper by NVIDIA](https://research.nvidia.com/sites/default/files/pubs/2019-07_Temporally-Dense-Ray//temporally-dense-ray-tracing.pdf) (see Page 2) and [paper by NIST.gov / NOKIA / Keltek](https://www.blurbusters.com/motion-tests/pursuit-camera-paper) (as coauthor), as well as other. Also, NVIDIA [recently commissioned Blur Busters](https://www.blurbusters.com/asus-and-nvidia-announce-360-hz-esports-displays-and-blur-busters-creates-custom-testufo-test/) to create a custom TestUFO test for the recent 360 Hz gaming monitor.  W3C [accepted my commit](https://github.com/w3c/html/commit/b7a916de2d9650331a12fbe433bb87e53a9e4f38) for a modification to HTML 5.2 specification (Section 7.1.4.2)

### Refresh Rates Is a New Frontier Of Tech Advancement

Just as 4K was niche (IBM T221 in 2001), it is now commoditized ($299 Walmart Black Friday).  This decade, 120 Hz is becoming commoditized in upcoming phones and displays.   

The spatial cow has been milked (**retina resolution**), and only now the temporal resolution cow has begun to be aggressively milked by industry (**retina refresh rates**).   Recent tests have shown that even 120Hz-vs-1000Hz has more human visible differences than 4K-versus-8K.  Even ASUS now has a roadmap to 1000Hz gaming monitors.  

Those unfamiliar with the benefits of refresh rate race (it even benefits browser scrolling, not just video games), can study [blurbusters.com/1000hz-journey](https://www.blurbusters.com/1000hz-journey) including its scientific references.  Other useful articles include [Frame Rate Amplification Technologies](https://www.blurbusters.com/frame-rate-amplification-technologies) which NVIDIA has confirmed they are working on; as well as [Stroboscopic Effect of Finite Frame Rate Displays](https://www.blurbusters.com/stroboscopics).  

### Upcoming Commoditization Of 120 Hz This Decade

The next iPhone and Galaxy will support 120 Hz refresh rates, accordingly to widely-reported sources.

Just as 120 Hz is about to become commoditized, future higher Hz will later become commoditized when costs (financial, power, efficiency, etc) and speed (e.g. GtG tiny fraction of refresh cycle duration) -- the human visible benefits become amplified.  

It is observed that 60Hz vs 120Hz on OLEDs is much more visible than 60Hz vs 120Hz on LCD.  Additionally, is observed that 60Hz vs 120Hz is much more visible on retina displays (more pixels to have artifacts over the same inch).    Tech progress has recently amplified the differences between refresh rates, and has created additiuonal pressures for higher refresh rates.   Refresh rates that were formerly bleeding edge (like retina resolution or 4K), are slowly being commoditized.

### Past Concerns are now Irrelevant

Efficiency is much higher, battery consumption is less of a concern in 2020 than 2017, compatibility became defacto standardized (as webpages made modifications) -- It is now time to formally standardize a WHATWG standards process for browser treatment of high refresh rates, in various arenas:
- requestAnimationFrame
- Browser scrolling (via touch, via mouse, via keyboard)
- WebGL
- CSS animations
- Etc

A broad-spectrum inclusion is required, much like what happened for retina resolution support, as processes needed to include all APIs (legacy and newer).

### Other References

Prior article about W3C standardization of other techs
https://www.blurbusters.com/blur-busters-working-on-changes-to-html-5-2/

Past article about 120 Hz Web Browser Benchmarking
https://www.blurbusters.com/blur-busters-120hz-web-browser-tests/

Recent article about 144 Hz Webkit support in non-Apple phones:
https://www.blurbusters.com/xiaomi-uses-testufo-to-demo-144-hz-redmi-5g-smartphone-apple-does-not-support-120-hz-testufo/

**Comment by domenic** [comment] 2020-01-16 23:10
Dupe of #158, looks like.

**Closed by domenic** 2020-01-16 23:10 UTC
